<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>promise try catch 不在同个事件循环，无法catch 到，只能promise 自带error 捕捉,Promise.all([]) 的用法,promise then catch 连续使用测试</title>
<meta name='viewport' content='width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no'/>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="" rel="stylesheet">
<script>
    //隐式拒绝，显式拒绝
    try{
        const promise=new Promise((resolve,reject)=>{
            const a=3;
            a=4;
            resolve();
        });
        promise.then(()=>{console.log('then is run');}).catch(e=>console.log('de'+' '+e)).then(()=>{console.log('dddddddddddddddddddddddd')});
    }
    catch(e){
        console.log(e);
    }

    //XMLHttpRequest 原生实现ajax
    function getJSON(url){
        return new Promise((resolve,reject)=>{
            const request=new XMLHttpRequest();
            request.open('GET',url);
            request.onload=function(){
                    if(this.status===200){
                        resolve(JSON.parse(this.response));
                    }
                    else{
                        reject(this.status + '  '+this.statusText);
                    }
            },
            request.onerror=()=>{
                reject(this.status+' '+this.statusText);
            }
            request.send();
        });
    }

    getJSON('./ajaxtest.json').then(res=>{
       alert(JSON.stringify(res));
    }).catch(e=>{
        console.log('异常');
        console.log(e);
    })


    //测试 Promise.all(promise1,promise2).then([a,b]=>{})  a,b 数据 怎么写

    function promise1(){
        return new Promise((resolve,reject)=>{
            reject(1)
        })
    }

    function promise2(){
        return new Promise((resolve,reject)=>{
            reject(2)
        })
    }

    Promise.all([promise1(),promise2()]).then(([a,b])=>{console.log(`测试结果：${a},${b}`)}).catch(e=>console.log(e))

    console.group('测试promise then，catch 连续使用')
        new Promise((resolve,reject)=>{
            // return resolve('A')
            return 'A';
        }).then(data=>{
            console.log(data)
            return 'B'
        }).then(data=>{
            console.log(data)
            throw('跑出错误')
        }).catch(e=>console.log(e))
    console.groupEnd()





   
</script>
</head>
<body>
    
</body>
</html>